apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato-app-deployment
  labels:
    app: zomato-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zomato-app
  template:
    metadata:
      labels:
        app: zomato-app
    spec:
      containers:
        - name: zomato
          image: rajveerkalra/zomato-clone-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: zomato-service
  labels:
    app: zomato-app
spec:
  type: NodePort
  selector:
    app: zomato-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000
