apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato-clone-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zomato-clone
  template:
    metadata:
      labels:
        app: zomato-clone
    spec:
      containers:
      - name: zomato
        image: rajveerkalra/zomato-clone-app
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: zomato-clone-service
spec:
  type: NodePort
  selector:
    app: zomato-clone
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
